<a href="https://colab.research.google.com/github/1998456/1998456/blob/main/R_PROGRAMMING(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## MATRIX

In [19]:
# Creating Matrices from 1-9 of 3 rows;
matrix(1:9, byrow=TRUE, nrow=3)

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6
[3,] 7    8    9

In [ ]:
# Creating Matrix from 1-27 in 9 rows;
matrix(1:27, byrow=TRUE, nrow=9)

      [,1] [,2] [,3]
 [1,]  1    2    3
 [2,]  4    5    6
 [3,]  7    8    9
 [4,] 10   11   12
 [5,] 13   14   15
 [6,] 16   17   18
 [7,] 19   20   21
 [8,] 22   23   24
 [9,] 25   26   27

## Analyzing Matrices

In [ ]:
# Box Office Star Wars;
new_hope <- c(460,314)
empire_strikes <- c(290,247)
return_jedi <- c(309,165)

In [ ]:
box_office <- c(new_hope, empire_strikes, return_jedi)
box_office

[1] 460 314 290 247 309 165

In [ ]:
star_wars_matrix= matrix(box_office,byrow=TRUE, nrow=3)

In [ ]:
star_wars_matrix

     [,1] [,2]
[1,] 460  314
[2,] 290  247
[3,] 309  165

Naming a Matrix

In [ ]:
# Countries Region & Title;
region <- c("US", "non-US")
title <- c("New Hope", "Empire Strikes", "Return of the Jedi")

In [ ]:
colnames(star_wars_matrix) <- region
rownames(star_wars_matrix) <- title

In [ ]:
star_wars_matrix

                   US  non-US
New Hope           460 314
Empire Strikes     290 247
Return of the Jedi 309 165

## Matrix Calculations

In [17]:
# Row Totals;using rowSums()function;
worldwide_vectors <- rowSums(star_wars_matrix)
worldwide_vectors

          New Hope     Empire Strikes Return of the Jedi
               774                537                474

Adding Columns & Rows to a Matrix

In [18]:
# Using cbind() function;
all_wars_matrix <- cbind(star_wars_matrix,worldwide_vectors)
all_wars_matrix

                   US  non-US worldwide_vectors
New Hope           460 314    774
Empire Strikes     290 247    537
Return of the Jedi 309 165    474

In [20]:
total_rev_vector <- colSums(star_wars_matrix)
total_rev_vector

    US non-US
  1059    726

In [24]:
# Using cbind() function;
all_wars_matrix1 <- cbind(all_wars_matrix,total_rev_vector)
all_wars_matrix1

Warning message in cbind(all_wars_matrix, total_rev_vector):
“number of rows of result is not a multiple of vector length (arg 2)”

                   US  non-US worldwide_vectors total_rev_vector
New Hope           460 314    774               1059
Empire Strikes     290 247    537                726
Return of the Jedi 309 165    474               1059

## Selection Of Matrix Elements

In [25]:
# Select the Non Us revenue for all movies;
non_us_all <- all_wars_matrix1[,2]

# Average Of non_us_revenue;
mean(non_us_all)

[1] 242

In [27]:
print(non_us_all)

          New Hope     Empire Strikes Return of the Jedi
               314                247                165

In [28]:
# Select the non_us_revenue for first two movies;
non_us_some <- all_wars_matrix[1:2,2]

# Averge non-us revenue for first two movies;
mean(non_us_some)

[1] 280.5

## Arithmetic With Matrices

In [29]:
# Column Division;
visitors <- all_wars_matrix1/5

visitors

                   US   non-US worldwide_vectors total_rev_vector
New Hope           92.0 62.8   154.8             211.8
Empire Strikes     58.0 49.4   107.4             145.2
Return of the Jedi 61.8 33.0    94.8             211.8