<a href="https://colab.research.google.com/github/1998456/1998456/blob/main/R_PROGRAMMING(5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DATAFRAME

# Looking at your dataset, using tail() & head() function;

In [17]:
# Creating a Dataframe;
planets <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet",
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209,3.4,5.4,0.6)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41,8.9,7.6,6.5)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

In [18]:
planets_df <- data.frame(planets, diameter, rotation, rings)
head(planets_df)

  planets diameter rotation rings
1 Mercury  0.382     58.64  FALSE
2 Venus    0.949   -243.02  FALSE
3 Earth    1.000      1.00  FALSE
4 Mars     0.532      1.03  FALSE
5 Jupiter 11.209      0.41   TRUE
6 Saturn   3.400      8.90   TRUE

In [19]:
# Gaining more insights in the Dataset;
str(planets_df)

'data.frame':	8 obs. of  4 variables:
 $ planets : chr  "Mercury" "Venus" "Earth" "Mars" ...
 $ diameter: num  0.382 0.949 1 0.532 11.209 ...
 $ rotation: num  58.64 -243.02 1 1.03 0.41 ...
 $ rings   : logi  FALSE FALSE FALSE FALSE TRUE TRUE ...

In [20]:
# Selection Of Dataframe Element;
planets_df[1:3,"type"]

NULL

In [21]:
planets_df[1:5,"diameter"]

[1]  0.382  0.949  1.000  0.532 11.209

In [24]:
# Selecting all Elements Of the Variable Diameter;METHOD(1)
planets_df[,3]
planets_df[,'diameter']

[1]   58.64 -243.02    1.00    1.03    0.41    8.90    7.60    6.50

[1]  0.382  0.949  1.000  0.532 11.209  3.400  5.400  0.600

In [25]:
# Selecting all Elements Of the Variable Diameter;METHOD(2)
planets_df$diameter

[1]  0.382  0.949  1.000  0.532 11.209  3.400  5.400  0.600

## Conditional Selection

In [26]:
# Selecting Planets With Rings;
planets_df[rings==TRUE,]

  planets diameter rotation rings
5 Jupiter 11.209   0.41     TRUE
6 Saturn   3.400   8.90     TRUE
7 Uranus   5.400   7.60     TRUE
8 Neptune  0.600   6.50     TRUE

In [27]:
# Performing Conditional Selection using Subset() function;
subset(planets_df,subset=rings)

# OR
subset(planets_df,subset=rings==TRUE)

  planets diameter rotation rings
5 Jupiter 11.209   0.41     TRUE
6 Saturn   3.400   8.90     TRUE
7 Uranus   5.400   7.60     TRUE
8 Neptune  0.600   6.50     TRUE

  planets diameter rotation rings
5 Jupiter 11.209   0.41     TRUE
6 Saturn   3.400   8.90     TRUE
7 Uranus   5.400   7.60     TRUE
8 Neptune  0.600   6.50     TRUE

In [28]:
# Selecting planets with diameter less than one;
subset(planets_df,subset=diameter<1)

  planets diameter rotation rings
1 Mercury 0.382      58.64  FALSE
2 Venus   0.949    -243.02  FALSE
4 Mars    0.532       1.03  FALSE
8 Neptune 0.600       6.50   TRUE

## Sorting a Dataframe;

In [29]:
# Using order() Function;
a <-  c(100,10,1000)
order(a)

[1] 2 1 3

In [30]:
a[order(a)]

[1]   10  100 1000

In [31]:
# Sorting Planets in a decreasing Order;
positions <- order(planets_df$diameter, decreasing=TRUE)
planets_df[positions,]

  planets diameter rotation rings
5 Jupiter 11.209      0.41   TRUE
7 Uranus   5.400      7.60   TRUE
6 Saturn   3.400      8.90   TRUE
3 Earth    1.000      1.00  FALSE
2 Venus    0.949   -243.02  FALSE
8 Neptune  0.600      6.50   TRUE
4 Mars     0.532      1.03  FALSE
1 Mercury  0.382     58.64  FALSE

# LIST

In [43]:
## Creating a List;
# Movie;
mov <- 'Shining'

# Act;
act <- c('jack','kane','kelvin','Ruth','kenny')

# Review;
rev <- data.frame('scores'= c(4.2,3.4,5.6),sources= c('imb1','imb2','imb3'),'reviews'= c('The movie seems great','it was scary though','i will say it was a bit funny'))

shining_list <- list(movie=mov,actor=act,reviews=rev)
shining_list

$movie
[1] "Shining"

$actor
[1] "jack"   "kane"   "kelvin" "Ruth"   "kenny"

$reviews
  scores sources                       reviews
1    4.2    imb1         The movie seems great
2    3.4    imb2           it was scary though
3    5.6    imb3 i will say it was a bit funny

# Selecting Elements In a Dataframe

In [44]:
# Selecting 1st element from 2nd Row;
shining_list[[2]][1]

[1] "jack"

In [45]:
# Selecting 1st,2nd & 3rd elements from 2nd column;
shining_list[[2]][1:3]

[1] "jack"   "kane"   "kelvin"

In [46]:
# Selecting Components;
shining_list[[3]]
shining_list$review
shining_list[[3]][2:3,]

  scores sources reviews
1 4.2    imb1    The movie seems great
2 3.4    imb2    it was scary though
3 5.6    imb3    i will say it was a bit funny

  scores sources reviews
1 4.2    imb1    The movie seems great
2 3.4    imb2    it was scary though
3 5.6    imb3    i will say it was a bit funny

  scores sources reviews
2 3.4    imb2    it was scary though
3 5.6    imb3    i will say it was a bit funny